### ISSUE TITLE
Does not recurse into subdirectories for the 'Add Books From Folder' option

### ISSUE THREAD

**Issue by kozross** [quaap/BookyMcBookface#10]
This seems like an odd design decision, as many people keep their books catalogued into subdirectories, which would require selecting each one individually, using an option meant to save time.

**Comment by donty** [comment]
Yes I agree, makes it difficult to find books in larger libraries. Would not have thought it difficult to follow down a path for valid book types. Is this being developed actively? If I get some time I might have a hack about and see if I can find anything but I am certainly no programmer... ;-)

**Comment by kozross** [comment]
@donty I don't know about active development - I haven't received any feedback from my issue, and there have been no commits for ~4 months now.

**Comment by quaap** [comment]
Hi! I'm back from the dead!  I've added this feature and it will be pushed in a new version sometime in the next week or two, if possible.

**Comment by kozross** [comment]
@quaap Good to hear!
