### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by FromSi** [quaap/BookyMcBookface#25]
Why the application does not use MT? (CardView and RecyclerView)

**Comment by quaap** [comment]
Oh.  The simple reason is I only have a limited amount of time to program.  I have two kids, one of whom is 3 and takes up most of my time, so when I do get a chance to program, I'm mostly interested in making just things work and be useful.  I've simply never taken the time to learn the things I need to do to make something Material Design-ed.  I also kind of enjoy the "cobbled together" look of the things I make :)  But maybe someday I'll fit better design into things.
