### ISSUE TITLE
Unclear Icon?

### ISSUE THREAD

**Issue by xgpt** [quaap/BookyMcBookface#27]
I see three icons and a "Contents" button. The top button is a checkbox with a square with a broken square around it. WHAT DOES THIS DO? So confused as it appears to change nothing, I'm not even sure which is the default mode. 

Lightbulb makes sense, so does magnifying glass, and so does contents, but this top button is unclear and highly perplexing.

Issue being placed for unclear UI/UX. Please clarify or consider adding a text description of what this button does.

Thank you.

**Comment by quaap** [comment]
When checked, it's supposed to make the reader view fullscreen.  Unchecked is not-fullscreen. I could change it to the "4 arrows pointing to corners" if that would be clearer.

One thing that could have added to your confusion is I noticed I have a bug where if you:
1) open that menu (which exits fullscreen),
2) then touch the screen off of the menu (which makes it fullscreen again),
3) _then_ uncheck the box, it does not exit fullscreen until you open the menu again.
