### ISSUE TITLE
Add Privacy.

### ISSUE THREAD

**Issue by HarryHeights** [quaap/BookyMcBookface#29]
Hello, I'm Harry.

I think it'll be awesome if you had a privacy policy that covers details of information collection and use when your software is utilized.

If you also think it's cool, I'd be glad to help in creating the document.

Would love to hear from you.

**Comment by quaap** [comment]
For this app it is easy: storage permission is used to read book files so you can read the books locally, and no data at all is transmitted outside of the app.  It doesn't even have internet permission.  You're welcome to write up a statement!

**Comment by HarryHeights** [comment]
Alright. Will document something right away.
