### ISSUE TITLE
Error opening epub epub (no sections)

### ISSUE THREAD

**Issue by beriain** [quaap/BookyMcBookface#32]
Hi!

I really like your app, it works quite well, and I love the fact that it's the only epub reader without internet permission I have found in F-droid.

Anyway, I downloaded an epub I can't open. The book is located here: https://framaclic.org/h/traces-epub
The error message says: "Something went wrong. Please report this book as a bug. (no sections)". I attach an screenshot:
![screenshot_2018-09-13-17-21-53](https://user-images.githubusercontent.com/7469634/45498544-83cddd00-b77a-11e8-8272-b27a0a27c449.png)
Thank you.

**Comment by quaap** [comment]
Thanks!  I've reproduced the problem, and figured out what was wrong (XML parsing problem). This fix will be in the next release.

**Comment by beriain** [comment]
Thank you very much! 

2018-09-17 22:31 egunean, Tom Kliethermes-(e)k idatzi du:

> Thanks! I've reproduced the problem, and figured out what was wrong (XML parsing problem). This fix will be in the next release. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/quaap/BookyMcBookface/issues/32#issuecomment-422160242
[2]
