### ISSUE TITLE
File not found on chapter select

### ISSUE THREAD

**Issue by edent** [quaap/BookyMcBookface#5]
Love the app! So quick. Minor problem on some books.

I loaded an ePub (converted with Calibre) and the book opened correctly. I was able to move between pages.

I clicked "CONTENTS" and got a list of Chapters.

I clicked on a chapter and got this error message.

![screenshot_20171003-074512](https://user-images.githubusercontent.com/837136/31114078-3b2a8a2e-a814-11e7-966d-0bc38dac9527.png)

```
The web page at 
file:///data/user/0/com.quaap.bookymcbookface/files/book_storage_emulated_0_Download_SEVENEVES%20-%20Neal%20Stephenson.epub/text%2Fpart0009.html 
could not be loaded because:

net::ERR_FILE_NOT_FOUND
```

Looking at `toc.ncx`, the corresponding chapter is

```
<navPoint class="chapter" id="num_8" playOrder="8">
   <navLabel>
      <text>Casting of Lots</text>
   </navLabel>
   <content src="text/part0009.html"/>
</navPoint>
```
Which appears to be correct.  The file `text/part0009.html` also exists.  This error occurs on all chapters in this ePub.  A book from Gutenberg works correctly.

Thanks once again for a great app.

**Comment by quaap** [comment]
Thanks!  Interesting. Can you attach an example of a failing book?

**Comment by owenh000** [comment]
@quaap, I am seeing this error too, with Booky McBookface 0.4.3.

Here is a test book that exhibits this behavior (gzipped for GitHub): [test.epub.gz](https://github.com/quaap/BookyMcBookface/files/4131885/test.epub.gz)

(Nice work on Booky McBookface; thanks!)

**Comment by owenh000** [comment]
I opened a new issue, #43.
