### ISSUE TITLE
Crash when I clic on the + button

### ISSUE THREAD

**Issue by JekoTronik** [quaap/BookyMcBookface#8]
I have installed v0.3.1 from FDroid. My phone is a Samsung Galaxy J5 with Android 6.0.1.

**Comment by quaap** [comment]
Strange.  I don't see that crash.  Is there something unusual about your device or set up?  Number of SD cards, etc?

**Comment by JekoTronik** [comment]
I have one 16G SD Card which is crypted (Android option, but I think it is transparent for the apps).

**Comment by Szostalo** [comment]
Same issue, Nexus 10, Android 5.1.1. Cannot add books.

**Comment by dperish** [comment]
Ditto. Galaxy S7 Edge stock, with 32gb unencrypted sd

**Comment by quaap** [comment]
I've located a possible culprit and added a fix.  Granted, I've not reproduced it, so I can't say for sure.  I pushed the changes (and others) just now, so whenever v0.3.3 hits F-Droid you can test it, or try it from [google play](https://play.google.com/store/apps/details?id=com.quaap.bookymcbookface) now.

**Comment by quaap** [comment]
Has anyone gotten any of the crashes when trying to find a book on version 0.3.5?
